version: '3.5'

services:
  # api:
  #   image: your-api-image:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_HOST=localhost
  #     - DB_PORT=3306
  #     - DATABASE=gk-games
  #     - USER=admin
  #     - PASSWORD=admin

  # websocket:
  #   image: your-websocket-image:latest
  #   ports:
  #     - "80:80"

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gk-games
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--transaction-isolation=READ-COMMITTED",
        "--binlog-format=ROW",
      ]
  redis:
    image: "redis:5.0.4"
    container_name: "redis"
    ports:
      - "6379:6379"

networks:
  gk-games:
    driver: bridge
